/**
 * Icon registry.
 *
 * Content files (src/content/*) refer to icons by *name* — a plain string — so that
 * editing the site never requires importing React components. To add an icon:
 *   1. import it from lucide-react below,
 *   2. add it to the `icons` map,
 * and it immediately becomes available to every content file.
 */
import {
  Award,
  BatteryCharging,
  Blocks,
  BookOpen,
  Brain,
  BriefcaseBusiness,
  Bug,
  Car,
  Cloud,
  Code2,
  Cpu,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  Fingerprint,
  Flame,
  Github,
  Globe2,
  GraduationCap,
  Languages,
  Layers,
  Leaf,
  Linkedin,
  LineChart,
  Lock,
  Mail,
  Map,
  MapPin,
  Mountain,
  Network,
  Phone,
  Plane,
  Radar,
  Send,
  Server,
  ShieldCheck,
  Sparkles,
  Terminal,
  Thermometer,
  TrendingUp,
  Trophy,
  UserRound,
  Users,
  Wrench,
  type LucideIcon,
} from 'lucide-react';

export const icons = {
  award: Award,
  battery: BatteryCharging,
  blocks: Blocks,
  book: BookOpen,
  brain: Brain,
  briefcase: BriefcaseBusiness,
  bug: Bug,
  car: Car,
  cloud: Cloud,
  code: Code2,
  cpu: Cpu,
  creditCard: CreditCard,
  database: Database,
  download: Download,
  external: ExternalLink,
  fingerprint: Fingerprint,
  flame: Flame,
  github: Github,
  globe: Globe2,
  graduation: GraduationCap,
  languages: Languages,
  layers: Layers,
  leaf: Leaf,
  linkedin: Linkedin,
  lineChart: LineChart,
  lock: Lock,
  mail: Mail,
  map: Map,
  mapPin: MapPin,
  mountain: Mountain,
  network: Network,
  phone: Phone,
  plane: Plane,
  radar: Radar,
  send: Send,
  server: Server,
  shield: ShieldCheck,
  sparkles: Sparkles,
  terminal: Terminal,
  thermometer: Thermometer,
  trending: TrendingUp,
  trophy: Trophy,
  user: UserRound,
  users: Users,
  wrench: Wrench,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export const getIcon = (name: IconName): LucideIcon => icons[name];
